name: Test
run-name: Linting and typechecking 🚀
env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
on:
  push:
  pull_request:
    branches:
      - 'main'

jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - run: yarn
      - run: yarn lint
  TypeChecking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - run: yarn
      - run: yarn typecheck
