name: Publish Package
run-name: Publishing Package to npmjs registry
env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
on:
  release:
    types: [published]
jobs:
  publishing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn
      - run: yarn npm publish
